### ISSUE TITLE
FR1. User login dashboard

### ISSUE THREAD

**Issue by ChristopherForkin36** [WSU-4110/ScheduleWorks#1]
|FR1.  User login dashboard|
|---|
|**Goal**: The user will be able to enter in their login and password and view their information. 
**Stakeholders:** Users|
| **Description:** When the user logins to the site, they will be able to view their class ranking, what year they are in, and what schedules they have currently (listed in numerical order or dependent on semester chosen). This feature of the system will just be a simple display, that can display information regarding the student prior to making a schedule. |
| **Origin:** While discussing what was needed in the first meeting, this requirement was brought up during the meeting as a useful feature that would assist users.|
| **Version:** 1.0  |  
|**Date:** 01/27/2023  
|  **Priority:** 1 |

**Comment by MMazenA** [comment]
Login shows user information now.
