### ISSUE TITLE
FR10. Generate future schedules 

### ISSUE THREAD

**Issue by ChristopherForkin36** [WSU-4110/ScheduleWorks#10]
|FR10. Generate future schedules        |
|---|
|**Goal**: The system will generate schedules for future semesters based on classes available at the time of generation.  
**Stakeholders:** Users|
| **Description:** Develop a viable 4–5-year plan with a customizable max-credit per semester option.  The software will produce a semester-by-semester plan for courses to take that would outline.  |
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |  
|**Date:** 01/27/2023  
|  **Priority:** 5 |

**Comment by AafnanM** [comment]
Not completed due to time constraints, the final application only generates a single schedule
