### ISSUE TITLE
FR11. Save user schedule information 

### ISSUE THREAD

**Issue by ChristopherForkin36** [WSU-4110/ScheduleWorks#11]
|FR11. Save user schedule information         |
|---|
|**Goal**: The system must save user information so that users can view and adjust generated schedules later. 
**Stakeholders:** Users|
| **Description:** Users will be able to save their generated schedules for later viewing. In addition, they can adjust and configure their previously saved schedules. These schedules will be saved under the user’s login.   |
| **Origin:**  Based on the initial project specification document, team members produced this description during the second meeting.|
| **Version:** 2.0  |  
|**Date:** 01/29/2023  
|  **Priority:** 7 |

**Comment by AafnanM** [comment]
Not completed due to time constraints, saving option is not present in the final application
