### ISSUE TITLE
FR12. Input menu for the user’s available days and times 

### ISSUE THREAD

**Issue by ChristopherForkin36** [WSU-4110/ScheduleWorks#12]
|FR12. Input menu for the user’s available days and times          |
|---|
|**Goal**: Users can input what days of the week and what times during each day they are available for classes. 
**Stakeholders:** Users|
| **Description:** Users will be able to select from a drop-down menu what days of the week and what times during each day that they are available, in case they have any other activities that occupy time such as jobs.    |
| **Origin:**  Based on the initial project specification document, team members produced this description during the second meeting.|
| **Version:** 2.0  |  
|**Date:** 01/29/2023  
|  **Priority:** 6 |

**Comment by AafnanM** [comment]
Not completed due to time constraints, the user is not presented with any availability options
