### ISSUE TITLE
FR13. Input menu for classes users would like to filter out 

### ISSUE THREAD

**Issue by ChristopherForkin36** [WSU-4110/ScheduleWorks#13]
|FR13. Input menu for classes users would like to filter out      |
|---|
|**Goal**: Users will be able to enter what classes they would like to filter out for a given semester.  
**Stakeholders:** Users|
| **Description:** Users will be introduced to an input menu where they can choose which classes they would prefer not to take in each semester, and the system will take this into account when generating a schedule. The system will treat the classes as a blacklist for the semester and ignore them.     |
| **Origin:**  Based on the initial project specification document, team members produced this description during the second meeting.|
| **Version:** 2.0  |  
|**Date:** 01/29/2023  
|  **Priority:** 8 |

**Comment by AafnanM** [comment]
Not completed due to time constraints, no filtering option is present in the final application
