### ISSUE TITLE
FR14. Website workflow after users log in 

### ISSUE THREAD

**Issue by ChristopherForkin36** [WSU-4110/ScheduleWorks#14]
|FR14. Website workflow after users log in          |
|---|
|**Goal**: After the user logs in to the website, allow the user to view past schedules or create a new schedule.  
**Stakeholders:** Users|
| **Description:** When the user logs onto the website they will be taken to a page with the option to view past schedules or create a new schedule. Viewing past schedules will allow the user to view schedules they have made from the past that are kept in our database. Creating a new schedule will allow the user to make a new schedule using our technology. Users will have the option to produce a new 4-year schedule or to produce a current year schedule to register for.      |
| **Origin:**  Based on the initial project specification document, team members produced this description during the second meeting.|
| **Version:** 3.0  |  
|**Date:** 01/29/2023  
|  **Priority:** 14 |

**Comment by AafnanM** [comment]
Not completed due to time constraints. Schedules are not saved in the final application, so users only have the option to create a new schedule
