### ISSUE TITLE
FR15. Allow users to report issues within the website 

### ISSUE THREAD

**Issue by ChristopherForkin36** [WSU-4110/ScheduleWorks#15]
|FR15. Allow users to report issues within the website           |
|---|
|**Goal**: Have a help button on the website that will allow users to report any issues they are having within the website.  
**Stakeholders:** System and Users|
| **Description:** A help button will be displayed on the website. If the help button is clicked on by the user, they will be taken to a page where they will be able to follow a process to report issues to the GitHub “Issues” page.    |
| **Origin:**  Based on the initial project specification document, team members produced this description during the second meeting.|
| **Version:** 3.0  |  
|**Date:** 01/29/2023  
|  **Priority:** 15 |

**Comment by MizanulH489** [comment]
Fulfilled with FAQ page that linked  to github help
