### ISSUE TITLE
NR1. Sensitive information authorization 

### ISSUE THREAD

**Issue by ChristopherForkin36** [WSU-4110/ScheduleWorks#16]
|NR1. Sensitive information authorization          |
|---|
|**Goal**: Users cannot access sensitive information without authorization. 
**Stakeholders:** All|
| **Description:** With this, we will ensure user information is kept secure and private. Only those with access will be given access to any sort of sensitive information for the users. Schedules of students will be kept private and secure.   |
| **Origin:**  Based on the initial project specification document, team members produced this description during the second meeting.|
| **Version:** 1.0  |  
|**Date:** 01/29/2023  
|  **Priority:** 1 |

**Comment by MMazenA** [comment]
Information is private to the users computer and no passwords are saved anywhere.
