### ISSUE TITLE
FR2. List of the user’s schedules

### ISSUE THREAD

**Issue by ChristopherForkin36** [WSU-4110/ScheduleWorks#2]
|FR2.  List of the user’s schedules|
|---|
|**Goal**: The system will provide users with the list of schedules that they have presently available to them, which is done after creating it. 
**Stakeholders:** Users|
| **Description:** When the user is on the dashboard after logging in, they will be able to view which schedules they have in an organized list. Users will be able to rename and reorganize the list according to their wishes. This feature will only be present to users after the system creates their personalized schedules, following their input.  |
| **Origin:** Based on initial project specification document, team members produced this description during the first meeting.|
| **Version:** 3.0  |  
|**Date:** 01/27/2023  
|  **Priority:** 11 |

**Comment by AafnanM** [comment]
Not completed due to time constraints, the final version only produces one schedule
