### ISSUE TITLE
NR5. The system should be accessible at all hours of the day 

### ISSUE THREAD

**Issue by ChristopherForkin36** [WSU-4110/ScheduleWorks#20]
|NR5. The system should be accessible at all hours of the day   |
|---|
|**Goal**: The software should be available to use during all hours of the day and if registration is open. | 
|**Stakeholders:** Users|
| **Description:** A user should be able to generate a new schedule during any hour of the day. It should be independent of the registration system and only offer a schedule that the user can manually register for.  |
| **Origin:** Based on the initial project specification document, team members produced this description during the second meeting.|
| **Version:** 2.0  |  
|**Date:** 01/29/2023  
|  **Priority:** 3 |

**Comment by MizanulH489** [comment]
System is independant
