### ISSUE TITLE
FR3.  Notification system for changes

### ISSUE THREAD

**Issue by ChristopherForkin36** [WSU-4110/ScheduleWorks#3]
|FR3.  Notification system for changes|
|---|
|**Goal**: The system present on the dashboard will present the user with any information regarding classes, and whether any modification of their schedule is needed. 
**Stakeholders:** Users|
| **Description:** Users will be able to see notifications on whether any classes they had were deleted, modified, or if any classes were added to a semester, which they can apply to their own schedule(s). Furthermore, if any classes are deleted, the system will show a notification on the dashboard.   |
| **Origin:** Following the initial presentation, we received feedback and decided to implement this after discussing it in the meeting.|
| **Version:** 3.0  |  
|**Date:** 01/27/2023  
|  **Priority:** 12 |

**Comment by AafnanM** [comment]
Not completed due to time constraints, no longer feasible since DegreeWorks API access was never given
