### ISSUE TITLE
FR4. Merge multiple schedules 

### ISSUE THREAD

**Issue by ChristopherForkin36** [WSU-4110/ScheduleWorks#4]
|FR4. Merge multiple schedules |
|---|
|**Goal**: This feature will allow users to merge any two or more schedules and create a new schedule out of all the classes they have on other schedules. 
**Stakeholders:** Users|
| **Description:** Users will be able to merge any schedules they have in their list into one newly created single schedule. This system will show any time overlap that will prevent this, offer students the ability to delete classes, and will place classes into open and available time slots that were requested during the initial creation from the user filtering it out.    |
| **Origin:** Based on initial project specification document, team members produced this description during the first meeting.|
| **Version:** 1.0  |  
|**Date:** 01/27/2023  
|  **Priority:** 2 |

**Comment by AafnanM** [comment]
Not completed due to time constraints, no merging feature present in the final application
