### ISSUE TITLE
FR6. Inputting and storing prior Classes 

### ISSUE THREAD

**Issue by ChristopherForkin36** [WSU-4110/ScheduleWorks#6]
|FR6. Inputting and storing prior Classes   |
|---|
|**Goal**: The function of this will be to input any classes that a user has taken previously that might not appear on ScheduleWorks.  
**Stakeholders:** Users|
| **Description:** The User will be able to input if he or she has completed some classes prior to the schedule generation. This can include classes a user has taken at a community college or AP classes taken during high school.     |
| **Origin:** Our group discuss the purpose of prior class and this function arose from it.|
| **Version:** 2.0  |  
|**Date:** 01/27/2023  
|  **Priority:** 10 |

**Comment by MizanulH489** [comment]
Due to time constraints, we were only able to add classes to schedule
