### ISSUE TITLE
FR8. Input menu specifying number of credits per semester 

### ISSUE THREAD

**Issue by ChristopherForkin36** [WSU-4110/ScheduleWorks#8]
|FR8. Input menu specifying number of credits per semester      |
|---|
|**Goal**: The system will ask the user how many credits they would ideally want to take in a certain semester.  
**Stakeholders:** Users|
| **Description:** Depending on factors such as full-time or part-time enrollment, in addition to how many credits a user is willing to take, users will need to be able to select the number of credits they will take. Users will be able to select this by semester through an input menu.      |
| **Origin:** There was a question asked during the presentation about how it can be calculated without knowing the Status of the student and that question emphasized the need for such function after discussing with the Team.|
| **Version:** 2.0  |  
|**Date:** 01/27/2023  
|  **Priority:** 9 |

**Comment by AafnanM** [comment]
Not completed due to time constraints, no input menus or filters are present in the final application
