### ISSUE TITLE
FR9. Rating system for schedules 

### ISSUE THREAD

**Issue by ChristopherForkin36** [WSU-4110/ScheduleWorks#9]
|FR9. Rating system for schedules       |
|---|
|**Goal**: The system will provide a rating for the generated schedule to convey to users how well the schedule would work given the parameters.  
**Stakeholders:** Users|
| **Description:** The user will be able to give ratings for their schedules to the Developing team directly, as the scores given for the schedules by the students will help identify which qualities worked best for the program.       |
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 3.0  |  
|**Date:** 01/27/2023  
|  **Priority:** 13 |

**Comment by MizanulH489** [comment]
Not completed due to to time constraints
